### ISSUE TITLE
error al iniciar el servicio

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/repo-backend#8]
El sevicio no inicia. si lo ejecuto manualmente tengo este error:

<pre>
repo@reprepro:/usr/share/repo-backend$ node index.js 

module.js:340
    throw err;
          ^
Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/repo-backend/debian_packages.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
</pre>

**Comment by iglosiggio** [comment]
Desde acá no puedo solucionarlo, pero tenés que instalar config.prod.js
como config.js
